## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key = g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Butaritari,KI,3.0707,172.7902,81.77,78,92,18.81,overcast clouds
1,1,Kiomboi,TZ,-4.2667,34.3667,60.80,59,26,15.17,scattered clouds
2,2,Prince Rupert,CA,54.3161,-130.3201,55.09,88,100,12.66,light rain
3,3,Punta Arenas,CL,-53.1500,-70.9167,33.91,93,100,8.05,snow
4,4,Ushuaia,AR,-54.8000,-68.3000,38.86,81,75,16.11,light rain
...,...,...,...,...,...,...,...,...,...,...
664,664,Lokosovo,RU,61.1333,74.8167,54.75,83,100,3.51,light rain
665,665,Nizhnevartovsk,RU,60.9344,76.5531,53.62,82,0,0.00,clear sky
666,666,Khomutovo,RU,52.4658,104.4025,59.61,95,60,2.48,broken clouds
667,667,Skovorodino,RU,53.9833,123.9167,61.56,99,100,3.38,light rain
668,668,Dudinka,RU,69.4058,86.1778,45.63,67,59,13.71,broken clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature for your vacation search? "))
max_temp = float(input("What is the maximum temperature for your vacation search? "))

What is the minimum temperature for your vacation search? 70
What is the maximum temperature for your vacation search? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Butaritari,KI,3.0707,172.7902,81.77,78,92,18.81,overcast clouds
5,5,Alassio,IT,44.0039,8.1671,78.06,75,2,1.99,clear sky
6,6,Albany,US,42.6001,-73.9662,86.58,48,19,12.95,few clouds
7,7,Houma,US,29.5958,-90.7195,77.00,88,0,3.44,clear sky
11,11,Puerto Ayora,EC,-0.7393,-90.3518,80.56,86,24,8.01,few clouds
...,...,...,...,...,...,...,...,...,...,...
658,658,Sakaiminato,JP,35.5500,133.2333,76.98,78,75,4.61,broken clouds
659,659,Satun,TH,6.8333,100.0000,75.20,97,100,5.06,overcast clouds
660,660,Half Moon Bay,US,37.4636,-122.4286,85.91,68,100,6.91,overcast clouds
661,661,Vilhena,BR,-12.7406,-60.1458,84.42,45,0,10.36,clear sky
663,663,Labuan,MY,5.2767,115.2417,79.16,88,20,2.30,few clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

# N.B.: This 4b does not apply to my situation because there is nothing to drop!

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = None
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Butaritari,KI,81.77,overcast clouds,3.0707,172.7902,None
5,Alassio,IT,78.06,clear sky,44.0039,8.1671,None
6,Albany,US,86.58,few clouds,42.6001,-73.9662,None
7,Houma,US,77.00,clear sky,29.5958,-90.7195,None
11,Puerto Ayora,EC,80.56,few clouds,-0.7393,-90.3518,None
...,...,...,...,...,...,...,...
658,Sakaiminato,JP,76.98,broken clouds,35.5500,133.2333,None
659,Satun,TH,75.20,overcast clouds,6.8333,100.0000,None
660,Half Moon Bay,US,85.91,overcast clouds,37.4636,-122.4286,None
661,Vilhena,BR,84.42,clear sky,-12.7406,-60.1458,None
663,Labuan,MY,79.16,few clouds,5.2767,115.2417,None

In [8]:
# Trying to clear an error by being redundant....
from config import g_key

In [9]:
# 6a. Set parameters to search for hotels with 5000 meters.

params = { 
    "radius": 5000,
    "type": "lodging",
    "key": g_key 
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Hotel not found.  City will be skipped.")

hotel_df.head(10)

Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.
Hotel not found.  City will be skipped.

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Butaritari,KI,81.77,overcast clouds,3.0707,172.7902,Isles Sunset Lodge
5,Alassio,IT,78.06,clear sky,44.0039,8.1671,Hotel Toscana
6,Albany,US,86.58,few clouds,42.6001,-73.9662,None
7,Houma,US,77.00,clear sky,29.5958,-90.7195,Courtyard by Marriott Houma
11,Puerto Ayora,EC,80.56,few clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
14,Humaita,BR,87.22,broken clouds,-7.5061,-63.0208,Corrêa Hotel
16,Gerash,IR,87.94,overcast clouds,27.6652,54.1371,Sa'adat House Gerash
17,Alofi,NU,78.69,broken clouds,-19.0595,-169.9187,Taloa Heights
19,Nagato,JP,73.85,overcast clouds,34.3833,131.2000,いそう庵
24,Vaini,TO,77.16,broken clouds,-21.2000,-175.2000,Keleti Beach Resort

In [14]:
# 7. Drop the rows where there is no Hotel Name.

clean_hotel_df = hotel_df.dropna()

clean_hotel_df.head(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Butaritari,KI,81.77,overcast clouds,3.0707,172.7902,Isles Sunset Lodge
5,Alassio,IT,78.06,clear sky,44.0039,8.1671,Hotel Toscana
7,Houma,US,77.00,clear sky,29.5958,-90.7195,Courtyard by Marriott Houma
11,Puerto Ayora,EC,80.56,few clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
14,Humaita,BR,87.22,broken clouds,-7.5061,-63.0208,Corrêa Hotel
16,Gerash,IR,87.94,overcast clouds,27.6652,54.1371,Sa'adat House Gerash
17,Alofi,NU,78.69,broken clouds,-19.0595,-169.9187,Taloa Heights
19,Nagato,JP,73.85,overcast clouds,34.3833,131.2000,いそう庵
24,Vaini,TO,77.16,broken clouds,-21.2000,-175.2000,Keleti Beach Resort
25,Arraial Do Cabo,BR,73.36,few clouds,-22.9661,-42.0278,Pousada Porto Praia
27,Goderich,CA,70.12,scattered clouds,43.7501,-81.7165,Harmony Inn
29,Kapaa,US,81.12,few clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
32,Puerto Escondido,MX,88.63,scattered clouds,15.8500,-97.0667,Aldea del Bazar Hotel and Spa
33,Rach Gia,VN,77.56,moderate rain,10.0167,105.0833,Nhà Hàng Hòa Giang
35,Ribeira Grande,PT,71.01,overcast clouds,38.5167,-28.7000,Quinta da Meia Eira
37,Aksu,CN,73.04,broken clouds,41.1231,80.2644,Pudong Holiday Hotel
40,Margate,GB,74.70,overcast clouds,51.3813,1.3862,Premier Inn Margate hotel
45,Kirakira,SB,80.89,broken clouds,-10.4544,161.9205,SanBiz Lodge
46,Salalah,OM,77.09,overcast clouds,17.0151,54.0924,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
47,Hithadhoo,MV,82.63,overcast clouds,-0.6000,73.0833,Scoop Guest House

In [15]:
# 8a. Create the output File (CSV)
output_data_file = "Hotel_CSV.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [16]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [17]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))